[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[project]
name = "apggr"
<<<<<<< HEAD
version = "1.0.1"
description = "A package for the analysis of population genetics for genomic regions (APGGR) targeting bacterial species."
authors = [{ name = "Limbani Thengo", email = "lthengo@gmail.com" }]
readme = "README.md"
=======
version = "1.0.0"
description = "A package for the analysis of population genetics for genomic regions (APGGR) targeting bacterial species."
authors = [{ name = "Limbani Thengo", email = "lthengo@gmail.com" }]
>>>>>>> a4b4075a8bdd4fcacdc55f1763b74eecdedafcc2
dependencies = [
  "biopython >= 1.84",
  "matplotlib >= 3.8.0",
  "numpy >= 1.26.4",
  "pandas >= 2.1.4",
  "scikit-learn >= 1.5.2",
]

[project.scripts]
apggr = "dispatcher:main"